# Generated by Django 3.2.15 on 2022-09-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_auto_20220908_1309"),
        ("mainapp", "0004_coursefeedback"),
    ]

    operations = []
